

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: data/Shiu/phantom4/train.txt
val: data/Shiu/phantom4/val.txt
test: data/Shiu/phantom4/test.txt

mesh: data/Shiu/phantom4/phantom4.ply
tr_range: data/Shiu/phantom4/training_range.txt
backup : backup/phantom4
names : ["phantom4"]

background_path: "data/VOCdevkit/VOC2012/JPEGImages"
coords: 18

diam : 0.522
gpus : 0

nc: 1  # number of classes

fx: 1979.4 
fy: 1979.1
u0: 976.8189
v0: 533.9717

